### ISSUE TITLE
Unable to get answers from the bot

### ISSUE THREAD

**Issue by jfuentesibanez** [Vortrix5/discord-ai-bot#1]
Hi!

I'm trying to get the bot working but, after, successfully configuring everything I keep getting this error when a message is sent to the bot using /ask:

```
Started refreshing 8 application (/) commands.
Successfully reloaded 8 application (/) commands.
TypeError: clearPrompt is not a function
    at Object.run (/Users/javier/Documents/Desarrollo/discord-gpt-bot-master/commands/gpt/ask.js:48:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.init (/Users/javier/Documents/Desarrollo/discord-gpt-bot-master/events/interactionCreate.js:38:17)
```

Do you know what could be happening?

Thanks in advance!

**Comment by Vortrix5** [comment]
Hello!

Thank you for reporting this issue. The fix is ready and pushed.

Feel free to message me if you have any other issue.

**Comment by jfuentesibanez** [comment]
Sorry to bother again @Vortrix5 but I don't know if I'm doing something in the wrong way. With your latest changes now I'm getting this error:

```
> discord-bot-boilerplate@1.2.0 start
> cross-env NODE_ENV=production NODE_NO_WARNINGS=1 node .

Ready! Logged in as Clayton.
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '../config.json'
Require stack:
- /Users/javier/Documents/Desarrollo/discord-gpt-bot-master/events/ready.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at Client.init (/Users/javier/Documents/Desarrollo/discord-gpt-bot-master/events/ready.js:68:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/javier/Documents/Desarrollo/discord-gpt-bot-master/events/ready.js'
  ]
}
```

It seems that config.json is not being found. Thank you very much for your time again!

**Comment by Vortrix5** [comment]
Hey!

You can try to manually generate the config.json file in your project. I will try to figure out on my end why it is not automatically being generated as it should be.

**Comment by jfuentesibanez** [comment]
Thanks, I created an empty config.json file (just with the {}) and now it works!
